################
### MONITORS ###
################

monitor=,preferred,auto,auto


#################
### AUTOSTART ###
#################

exec-once = kitty
exec-once = waybar
exec-once = /usr/local/bin/hyprpaper
exec-once = swaync
exec-once = tailscale systray
exec-once = ~/.config/hypr/scripts/WallSwitcher.sh

#############################
### ENVIRONMENT VARIABLES ###
#############################


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME, qt6ct

#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 0.9
    inactive_opacity = 0.8

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 1
        passes = 1

        vibrancy = 0.1696
    }
}

animations {
    enabled = yes
    # The Curves
    bezier = snap, 0.16, 0.37, 0.26, 1.42
    bezier = smooth, 0.44, 0.14, 0.38, 0.69

    # The Applications of the curves
    animation = workspaces, 1, 2, snap
    animation = windowsMove, 1, 1, smooth
    animation = windowsIn, 1, 1.2, smooth, popin 10%
    animation = windowsOut, 1, 1.7, smooth, popin 10%
    animation = global, 1, 10, default

}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
}


#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

###################
### SOURCES ###
###################

source = keybinds.conf
source = other.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
